services:
    sonata.admin.feedback:
        class: %grossum_feedback.feedback.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.main, label: "Обратная связь" }
        arguments:
            - ~
            - %grossum_feedback.feedback.entity.class%
            - ~