Grossum\FeedbackBundle\Entity\Feedback:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 30
            - Regex: '/^\w+/'
        email:
            - NotBlank: ~
            - Length:
                min: 3
                max: 30
            - Regex: '/^\w+/'
            - Email:
                strict: true
                checkMX: true
                checkHost: true
        message:
            - NotBlank: ~